server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-user
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    addresses: amqps://occvhbem:xmMmD9UJgrPJZ_av8kozrZAbaoiZ0RXB@woodpecker.rmq.cloudamqp.com/occvhbem

broker:
  queue:
    email:
      name: default.email